const agenda_fr = {
  title: "Agenda",
  ticker: "dates",
  year_2022: {
    year: 2022,
    imgss_2: {
      type: "résidence",
      type_href: "/fr/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "5-16déc",
      institution: "Ottawa Dance Directive",
      institution_href: "https://odd-cdc.org/fr/",
      place: "Ottawa",
    },
    imgss: {
      type: "résidence",
      type_href: "/fr/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "22-28aoû",
      institution: "La Chapelle",
      institution_href: "https://lachapelle.org/fr/programmation/residence",
      place: "Montréal / Tiohtiá:ke",
    },

    innovating_circus_technique: {
      type: "pédagogie",
      type_href: "/fr/pgogy",
      title: "Innover la technique circassienne",
      dates: "jan-avr",
      institution: "ENC",
      institution_href: "https://ecolenationaledecirque.ca/fr",
      place: "Montréal / Tiohtiá:ke",
    },
  },
  year_2021: {
    year: 2021,
    montreal_danse: {
      type: "résidence",
      type_href: "/fr/collab",
      title: "Recherche Chorégraphique / Sarah Manya",
      dates: "13-17déc",
      institution: "Montréal Danse",
      institution_href: "https://montrealdanse.com/new2/fr/",
      place: "Montréal / Tiohtiá:ke",
    },
    chita_sutton: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "26-28oct",
      institution: "D'Arts et de rêves",
      institution_href: "https://dartsetdereves.org/en/",
      place: "Sutton, QC",
      type: "résidence",
      type_href: "/fr/collab",
    },
    danse_cite: {
      title: "Through us ( comme espace ) passions .pt2",
      institution_href: "https://danse-cite.org/",
      dates: "18-22oct",
      institution: "Danse-Cité / The Mainline",

      place: "Montréal / Tiohtiá:ke",
      type: "résidence",
      type_href: "/fr/collab",
    },
    ccov: {
      title: "Semaine d'écriture",
      institution_href: "https://ccov.org/",
      dates: "12-15oct",
      institution: "CCOV",

      place: "Montréal / Tiohtiá:ke",
      type: "résidence d;écriture",
      type_href: "/fr/collab",
    },
    topical_danse: {
      title: "Topical Dance",
      place: "Montréal / Tiohtiá:ke",
      project_href_int: "/fr/works",
      institution: "LE PACA",
      institution_href: "https://lesfoutoukours.com/fr/paca/",
      dates: "29sep-3oct",
      type: "résidence",
      type_href: "/fr/works",
    },
    lowest_parts_2: {
      title: "the lowest parts",
      project_href: "https://emilepineault.com/projects/2022-the-lowest-parts/",
      place: "Montréal / Tiohtiá:ke",
      institution: "Studio 303",
      institution_href: "https://www.studio303.ca/category/residencies/",
      dates: "14-16jul",
      type: "résidence",
      type_href: "/fr/collab",
    },
    funfunfunfunfun: {
      title: "funfunfunfunfun",
      place: "Montréal / Tiohtiá:ke",
      project_href:
        "https://montrealcompletementcirque.com/fr/programmation/spectacles/fun-fun-fun-fun-fun/",
      institution: "Montéal Complètement Cirque",
      institution_href: "https://montrealcompletementcirque.com/fr/",
      dates: "7-13jul",
      type: "représentations (dramaturgie)",
      type_href: "/fr/collab",
    },
    chita_cds: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "14-18jun",
      institution: "La Tohu",
      institution_href: "https://tohu.ca/en",
      place: "Montréal / Tiohtiá:ke",
      type: "résidence",
      type_href: "/fr/collab",
    },
    uca: {
      title: "Une caresse animée",
      project_href: "http://www.acrobatetoimeme.com",
      dates: "31mai-4jun",
      institution: "OFFTA / La Serre",
      institution_href: "https://offta.com/evenement2021/francois-bouvier/",
      place: "Montréal / Tiohtiá:ke",
      type: "représentations (dramaturgie)",
      type_href: "/fr/collab",
    },
    uca_avantP: {
      title: "Une caresse animée",
      project_href: "http://www.acrobatetoimeme.com",
      dates: "4-6mai",
      institution: "L'avant-première",
      institution_href: "https://avantpremiere.ca/",
      place: "Gatineau, QC",
      type: "résidence",
      type_href: "/fr/collab",
    },
    chita_cds_2: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "19-23avr",
      institution: "La Tohu",
      institution_href: "https://tohu.ca/en",
      place: "Montréal / Tiohtiá:ke",
      type: "résidence",
      type_href: "/fr/collab",
    },
    lowest_parts: {
      title: "the lowest parts",
      project_href: "https://emilepineault.com/projects/2022-the-lowest-parts/",
      institution: "Circuit Est",
      institution_href:
        "https://circuit-est.qc.ca/en/activity/support-for-creation/",
      place: "Montréal / Tiohtiá:ke",
      dates: "29-31mar",
      type: "résidence",
      type_href: "/fr/collab",
    },
    choreographing_touch: {
      title: "Choreographing Touch - Conversations",
      project_href:
        "https://www.spreaker.com/show/choreographing-touch-conversations",
      dates: "3mar-7avr",
      type: "baladodiffusion",
      type_href: "/fr/works",
      place: "Montréal / Tiohtiá:ke, Brussels, Amsterdam, London",
    },
    care: {
      title: "Circus Dialogues - Matters of Care",
      project_href:
        "https://m.facebook.com/events/d41d8cd9/public-book-club-matters-of-care/424964351852234/",
      dates: "12fév",
      institution: "KASK",
      institution_href: "https://schoolofartsgent.be/2021/?lang=en",
      type: "discussion",
      type_href: "/fr/collab",
      place: "Montréal / Tiohtiá:ke, Bruxelles, Londres, Stockholm",
    },
  },
  year_2020: {
    year: 2020,
    kaai: {
      title: "Un-Staging Tactility",
      dates: "22mai",
      project_href: "https://www.veratussing.com/",
      institution: "KAAI",
      institution_href: "https://www.kaaitheater.be/en",
      place: "Bruxelles",
      type: "résidence",
      type_href: "/fr/collab",
    },
    imgss: {
      title: "I miss Grandma so sad",
      dates: "17-21fév",
      project_href: "http://www.acrobatetoimeme.com",
      institution: "Circuscentrum",
      institution_href: "https://www.circuscentrum.be/",
      type: "résidence",
      type: "/fr/collab",
      place: "Gand",
    },
    ab_degrotepost: {
      title: "Always / Beautiful",
      dates: "6fév",
      project_href: "https://manorhouseforever.net/performances",
      institution: "De Grote Post",
      institution_href:
        "https://www.degrotepost.be/agenda/1974/Manor_House/Always_Beautiful/",
      place: "Ostende",
      type: "représentation (interprétation)",
      type_href: "/fr/works",
    },
    circusdialogues_symp: {
      title:
        "Smells Like Dialogue + Vernissage du livre 'Thinking Through Circus'",
      dates: "13-17jan",
      project_href: "https://www.circusdialogue.com/gallery",
      institution: "Voo?uit",
      institution_href:
        "https://www.vooruit.be/en/agenda/2365/A_Circus_Symposium/Smells_like_Dialogue/",
      place: "Ghent",
      type: "symposium/semaine de recherche",
      type_href: "/frworks",
    },
  },
  year_2019: {
    year: 2019,
    imgss: {
      title: "I miss Grandma so sad",
      dates: "11-15nov",
      project_href: "http://www.acrobatetoimeme.com",
      institution: "Les Noctambules",
      institution_href: "https://www.les-noctambules.com/fr/accueil.html",
      type: "résidence",
      type_href: "/frcollab",
      place: "Paris",
    },
    ab: {
      title: "Always / Beautiful",
      dates: "11-15nov",
      project_href: "https://manorhouseforever.net/performances",
      institution: "Theater op de Markt",
      institution_href:
        "https://www.theateropdemarkt.be/programma/programmaboek/",
      type: "performance/premiere",
      type_href: "/frworks",
      place: "Neerpelt, BE",
    },
  },
};
module.exports = {
  agenda_fr,
};
