const agenda_en = {
  title: "Dates",
  ticker: "dates",
  year_2023: {
    year: 2023,
    td_tangente2: {
      type: "performance/work-in-progress",
      type_href: "/en/works",
      title: "Topical Dance",
      project_href: "/en/works",
      dates: "11-13nov",
      institution: "Tangente",
      institution_href: "https://tangentedanse.ca/en/",
      place: "Montréal / Tiohtiä:ke",
    },
    td_tangente: {
      type: "residency",
      type_href: "/en/works",
      title: "Topical Dance",
      project_href: "/en/works",
      dates: "fall2022",
      institution: "Tangente",
      institution_href: "https://tangentedanse.ca/en/submit-a-project/",
      place: "Montréal / Tiohtiä:ke",
    },
    td_rouyn: {
      type: "residency",
      type_href: "/en/works",
      title: "Topical Dance",
      project_href: "/en/works",
      dates: "summer2022",
      institution: "Annexe A",
      institution_href: "https://www.lannexe-a.com/",
      place: "Rouyn-Noranda, QC",
    },
    td_belgium: {
      type: "residency",
      type_href: "/en/works",
      title: "Topical Dance",
      project_href: "/en/works",
      dates: "6-19mar",
      institution: "Workspacebrussels",
      institution_href: "https://www.workspacebrussels.be/",
      place: "Brussels",
    },
    imgss_premiere: {
      type: "performance/premiere",
      type_href: "/en/collab",
      title: "I miss grandma so Sad",
      project_href: "https://lachapelle.org/en/schedule/i-miss-grandma-so-sad",
      dates: "20-23feb",
      institution: "La Chapelle",
      institution_href:
        "https://lachapelle.org/en/schedule/i-miss-grandma-so-sad",
      place: "Montréal / Tiohtiä:ke",
    },
    dramaturgy_workshop: {
      type: "teaching",
      type_href: "/en/pgogy",
      title: "Mise en scène dramaturgique",
      project_href:
        "https://casjb.com/formations/mise-en-scene-dramaturgique-pour-le-cirque-et-les-arts-performatifs/",
      dates: "4-5feb",
      institution: "Centre des arts de la scène Jean Besré",
      institution_href:
        "https://casjb.com/formations/mise-en-scene-dramaturgique-pour-le-cirque-et-les-arts-performatifs/",
      place: "Sherbrooke, QC",
    },
  },
  year_2022: {
    year: 2022,
    imgss_2: {
      type: "residency",
      type_href: "/en/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "5-16dec",
      institution: "Ottawa Dance Directive",
      institution_href: "https://odd-cdc.org/",
      place: "Ottawa",
    },
    montreal_danse: {
      type: "residency",
      type_href: "/en/collab",
      title: "Choreographic Research / Sarah Manya",
      dates: "fall2022",
      institution: "Montréal Danse",
      institution_href: "https://montrealdanse.com/new2/",
      place: "Montréal / Tiohtiá:ke",
    },
    td_flak: {
      type: "residency",
      type_href: "/en/works",
      title: "Topical Dance",
      project_href: "en/works",
      dates: "fall2022",
      institution: "Cie José Navas / Diagramme",
      institution_href: "https://diagramme.org/studios-solidaires/",
      place: "Montréal / Tiohtiá:ke",
    },
    imgss: {
      type: "residency",
      type_href: "/en/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "22-28aug",
      institution: "La Chapelle",
      institution_href: "https://lachapelle.org/en/schedule/residencies",
      place: "Montréal / Tiohtiá:ke",
    },
    thinginitself_premiere: {
      type: "performance/premiere",
      type_href: "/en/collab",
      title: "The thing in itself",
      project_href: "https://lachapelle.org/en/schedule/the-chita-project",
      dates: "11-12jul",
      institution: "La Chapelle Scènes Contemporaines",
      institution_href: "https://lachapelle.org/en/schedule/the-chita-project",
      place: "Montréal / Tiohtiä:ke",
    },
  },
  year_2021: {
    year: 2021,
    montreal_danse: {
      type: "residency",
      type_href: "/en/collab",
      title: "Choreographic Research / Sarah Manya",
      dates: "13-17dec",
      institution: "Montréal Danse",
      institution_href: "https://montrealdanse.com/new2/",
      place: "Montréal / Tiohtiá:ke",
    },
    chita_sutton: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "26-28oct",
      institution: "D'Arts et de rêves",
      institution_href: "https://dartsetdereves.org/en/",
      place: "Sutton, QC",
      type: "residency",
      type_href: "/en/collab",
    },
    danse_cite: {
      title: "Through us ( comme espace ) passions .pt2",
      institution_href: "https://danse-cite.org/en/",
      dates: "18-22oct",
      institution: "Danse-Cité / The Mainline",

      place: "Montréal / Tiohtiá:ke",
      type: "residency",
      type_href: "/en/collab",
    },
    ccov: {
      title: "Writing week",
      institution_href: "https://ccov.org/en/",
      dates: "12-15oct",
      institution: "CCOV",

      place: "Montréal / Tiohtiá:ke",
      type: "writing residency",
      type_href: "/en/collab",
    },
    topical_danse: {
      title: "Topical Dance",
      place: "Montréal / Tiohtiá:ke",
      project_href_int: "/en/works",
      institution: "LE PACA",
      institution_href: "https://lesfoutoukours.com/fr/paca/",
      dates: "29sep-3oct",
      type: "residency",
      type_href: "/en/works",
    },
    lowest_parts_2: {
      title: "the lowest parts",
      project_href: "https://emilepineault.com/projects/2022-the-lowest-parts/",
      place: "Montréal / Tiohtiá:ke",
      institution: "Studio 303",
      institution_href: "https://www.studio303.ca/en/category/residencies/",
      dates: "14-16jul",
      type: "residency",
      type_href: "/en/collabs",
    },
    funfunfunfunfun: {
      title: "funfunfunfunfun",
      place: "Montréal / Tiohtiá:ke",
      project_href:
        "https://montrealcompletementcirque.com/en/program/shows/fun-fun-fun-fun-fun/",
      institution: "Montéal Complètement Cirque",
      institution_href: "https://montrealcompletementcirque.com/en/",
      dates: "7-13jul",
      type: "shows (dramaturgy)",
      type_href: "/en/collabs",
    },
    chita_cds: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "14-18jun",
      institution: "La Tohu",
      institution_href: "https://tohu.ca/en",
      place: "Montréal / Tiohtiá:ke",
      type: "residency",
      type_href: "/en/collab",
    },
    uca: {
      title: "Une caresse animée",
      project_href: "http://www.acrobatetoimeme.com",
      dates: "31may-4jun",
      institution: "OFFTA / La Serre",
      institution_href: "https://offta.com/evenement2021/francois-bouvier/",
      place: "Montréal / Tiohtiá:ke",
      type: "shows (dramaturgy)",
      type_href: "/en/collab",
    },
    uca_avantP: {
      title: "Une caresse animée",
      project_href: "http://www.acrobatetoimeme.com",
      dates: "4-6may",
      institution: "L'avant-première",
      institution_href: "https://avantpremiere.ca/",
      place: "Gatineau, QC",
      type: "residency",
      type_href: "/en/collab",
    },
    chita_cds_2: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "19-23apr",
      institution: "La Tohu",
      institution_href: "https://tohu.ca/en",
      place: "Montréal / Tiohtiá:ke",
      type: "residency",
      type_href: "/en/collab",
    },
    lowest_parts: {
      title: "the lowest parts",
      project_href: "https://emilepineault.com/projects/2022-the-lowest-parts/",
      institution: "Circuit Est",
      institution_href:
        "https://circuit-est.qc.ca/en/activity/support-for-creation/",
      place: "Montréal / Tiohtiá:ke",
      dates: "29-31mar",
      type: "residency",
      type_href: "/en/collabs",
    },
    choreographing_touch: {
      title: "Choreographing Touch - Conversations",
      project_href:
        "https://www.spreaker.com/show/choreographing-touch-conversations",
      dates: "3mar-7apr",
      type: "podcasting",
      type_href: "/en/works",
      place: "Montréal / Tiohtiá:ke, Brussels, Amsterdam, London",
    },
    care: {
      title: "Circus Dialogues - Matters of Care",
      project_href:
        "https://m.facebook.com/events/d41d8cd9/public-book-club-matters-of-care/424964351852234/",
      dates: "12feb",
      institution: "KASK",
      institution_href: "https://schoolofartsgent.be/2021/?lang=en",
      type: "discussion",
      type_href: "/en/collabs",
      place: "Montréal / Tiohtiá:ke, Brussels, London, Stockholm",
    },
  },
  year_2020: {
    year: 2020,
    kaai: {
      title: "Un-Staging Tactility",
      dates: "22may",
      project_href: "https://www.veratussing.com/",
      institution: "KAAI",
      institution_href: "https://www.kaaitheater.be/en",
      place: "Brussels",
      type: "residency",
      type_href: "/en/collabs",
    },
    imgss: {
      title: "I miss Grandma so sad",
      dates: "17-21feb",
      project_href: "http://www.acrobatetoimeme.com",
      institution: "Circuscentrum",
      institution_href: "https://www.circuscentrum.be/",
      type: "residency",
      type: "/en/collabs",
      place: "Ghent",
    },
    ab_degrotepost: {
      title: "Always / Beautiful",
      dates: "6feb",
      project_href: "https://manorhouseforever.net/performances",
      institution: "De Grote Post",
      institution_href:
        "https://www.degrotepost.be/agenda/1974/Manor_House/Always_Beautiful/",
      place: "Oostende",
      type: "performance",
      type_href: "/en/works",
    },
    circusdialogues_symp: {
      title: "Smells Like Dialogue + Book Launch 'Thinking Through Circus'",
      dates: "13-17jan",
      project_href:
        "https://artpapereditions.org/products/bauke-lievens-quintijn-ketels-sebastian-kann-vincent-focquet-eds-thinking-through-circus",
      institution: "viernulvier",
      institution_href: "https://www.viernulvier.gent/en/",
      place: "Ghent",
      type: "symposium/work week",
      type_href: "/en/works",
    },
  },
  year_2019: {
    year: 2019,
    imgss: {
      title: "I miss Grandma so sad",
      dates: "11-15nov",
      project_href: "http://www.acrobatetoimeme.com",
      institution: "Les Noctambules",
      institution_href: "https://www.les-noctambules.com/fr/accueil.html",
      type: "residency",
      type_href: "/en/collabs",
      place: "Paris",
    },
    ab: {
      title: "Always / Beautiful",
      dates: "11-15nov",
      project_href: "https://manorhouseforever.net/performances",
      institution: "Theater op de Markt",
      institution_href:
        "https://www.theateropdemarkt.be/programma/programmaboek/",
      type: "performance/premiere",
      type_href: "/en/works",
      place: "Neerpelt, BE",
    },
  },
};

module.exports = {
  agenda_en,
};
