const agenda_en = {
  title: "Dates",
  ticker: "dates",
  year_2022: {
    year: 2022,
    imgss_2: {
      type: "residency",
      type_href: "/en/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "5-16dec",
      institution: "Ottawa Dance Directive",
      institution_href: "https://odd-cdc.org/",
      place: "Ottawa",
    },
    imgss: {
      type: "residency",
      type_href: "/en/collab",
      title: "I miss grandma so Sad",
      project_href: "https://www.acrobatetoimeme.com/",
      dates: "22-28aug",
      institution: "La Chapelle",
      institution_href: "https://lachapelle.org/fr/programmation/residence",
      place: "Montréal / Tiohtiá:ke",
    },

    innovating_circus_technique: {
      type: "teaching",
      type_href: "/en/pgogy",
      title: "Innovating circus technique",
      dates: "jan-apr",
      institution: "ENC",
      institution_href: "https://ecolenationaledecirque.ca/en",
      place: "Montréal / Tiohtiá:ke",
    },
  },
  year_2021: {
    year: 2021,
    montreal_danse: {
      type: "residency",
      type_href: "/en/collab",
      title: "Choreographic Research / Sarah Manya",
      dates: "13-17dec",
      institution: "Montréal Danse",
      institution_href: "https://montrealdanse.com/new2/",
      place: "Montréal / Tiohtiá:ke",
    },
    chita_sutton: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "26-28oct",
      institution: "D'Arts et de rêves",
      institution_href: "https://dartsetdereves.org/en/",
      place: "Sutton, QC",
      type: "residency",
      type_href: "/en/collab",
    },
    danse_cite: {
      title: "Espace recherche",
      institution_href: "https://danse-cite.org/",
      dates: "18-22oct",
      institution: "Danse-Cité / The Mainline",

      place: "Montréal / Tiohtiá:ke",
      type: "residency",
      type_href: "/en/collab",
    },
    ccov: {
      title: "Writing week",
      institution_href: "https://ccov.org/",
      dates: "12-15oct",
      institution: "CCOV",

      place: "Montréal / Tiohtiá:ke",
      type: "writing residency",
      type_href: "/en/collab",
    },
    topical_danse: {
      title: "Topical Dance",
      project_href_int: "/en/works",
      institution: "LE PACA",
      institution_href: "https://lesfoutoukours.com/fr/paca/",
      dates: "29sep-3oct",
      type: "residency",
      type_href: "/en/works",
    },
    funfunfunfunfun: {
      title: "funfunfunfunfun",
      project_href:
        "https://montrealcompletementcirque.com/en/program/shows/fun-fun-fun-fun-fun/",
      institution: "Montéal Complètement Cirque",
      institution_href: "https://montrealcompletementcirque.com/en/",
      dates: "7-15jul",
      type: "shows (dramaturgy)",
      type_href: "/en/collabs",
    },
    chita_cds: {
      title: "La chose en soi",
      project_href: "https://www.facebook.com/thechitaproject/",
      dates: "14-18jun",
      institution: "La Tohu",
      institution_href: "https://tohu.ca/en",
      place: "Montréal / Tiohtiá:ke",
      type: "residency",
      type_href: "/en/collab",
    },
    uca: {
      title: "Une caresse animée",
      project_href: "www.acrobatetoimeme.com",
      dates: "4-6may",
      institution: "OFFTA / La Serre",
      institution_href: "https://offta.com/evenement2021/francois-bouvier/",
      place: "Montréal / Tiohtiá:ke",
      type: "shows (dramaturgy)",
      type_href: "/en/collab",
    },
    uca_avantP: {
      title: "Une caresse animée",
      project_href: "www.acrobatetoimeme.com",
      dates: "14-18jun",
      institution: "L'avant-première",
      institution_href: "https://avantpremiere.ca/",
      place: "Gatineau, QC",
      type: "residency",
      type_href: "/en/collab",
    },
  },
};

module.exports = {
  agenda_en,
};
